-- 
-- Volcar la base de datos para la tabla `/*prefijo_db*/bloque`
-- 

INSERT INTO `/*prefijo_db*/bloque` (`id_bloque`, `nombre`, `descripcion`, `grupo`) VALUES 
(1, 'login_principal', 'Interfaz Grafica para la pagina principal del aplicativo que contiene la funcionalidad de autenticacion.', 'general'),
(2, 'registro_usuario', 'Bloque para el formulario de registro de usuarios.', 'REGISTRO'),
(3, 'registro_rol', 'Formulario para seleccion de rol', 'REGISTRO'),
(4, 'banner', 'Bloque con el banner por defecto del aplicativo.', 'GRAFICO'),
(5, 'pie', 'Pie de pagina por defecto del aplicativo', 'GRAFICO'),
(6, 'login', 'Bloque para la autenticacion de usuarios desde las paginas del tour', 'FORMULARIO'),
(7, 'logout', 'Bloque para gestionar la terminacion de sesiones.', 'MENU'),
(8, 'mensaje', 'Bloque general con el que se gestionan los diferentes mensajes que se presentan en el sistema.', 'GENERAL'),
(9, 'menu_admin', 'Menu principal del modulo de administracion', 'MENU'),
(10, 'admin_usuario', 'Bloque para mostrar los registros de usuario que cumplan ciertos criterios de busqueda', 'ADMINISTRACION'),
(11, 'menu_admin_usuario', 'Menu principal de la seccion de administracion de usuarios', 'MENU'),
(12, 'borrar_registro', 'Bloque para la eliminación de registros en el sistema', ''),
(13, 'menu_entidad', 'Menu principal del modulo de entidades de salud.', 'MENU'),
(14, 'admin_entidad', 'Muestra los registros de las entidades existentes.', 'ADMIN'),
(15, 'menu_registro_entidad', 'Menu', 'MENU'),
(16, 'registro_entidad', 'Bloque para el registro de entidades de salud.', 'REGISTRO'),
(17, 'menu_info_entidad', 'Menu para la seleccion de opciones de mas informacion para las entidades', 'MENU'),
(18, 'menu_servicios', 'Menu principal del subsistema de servicios medicos', 'SERVICIOS'),
(19, 'admin_especialidad', 'Bloque para mostrar las diferentes especilaidades medicas registradas en el SITEM', 'ADMIN'),
(20, 'menu_registro_especialidad', NULL, 'MENU'),
(21, 'registro_especialidad', NULL, 'REGISTRO'),
(22, 'admin_procedimiento', 'Listado de procedimientos medicos', 'ADMIN'),
(23, 'menu_registro_procedimiento', NULL, 'MENU');

-- 
-- Volcar la base de datos para la tabla `/*prefijo_db*/bloque_pagina`
-- 

INSERT INTO `/*prefijo_db*/bloque_pagina` (`id_pagina`, `id_bloque`, `seccion`, `posicion`) VALUES 
(1, 1, 'A', 1),
(2, 2, 'C', 1),
(3, 3, 'C', 1),
(2, 4, 'A', 1),
(2, 5, 'E', 1),
(2, 6, 'B', 1),
(5, 4, 'A', 1),
(5, 5, 'E', 1),
(5, 8, 'C', 1),
(5, 9, 'B', 1),
(5, 7, 'B', 2),
(6, 7, 'C', 1),
(7, 4, 'A', 1),
(7, 5, 'E', 1),
(7, 9, 'B', 1),
(7, 7, 'B', 2),
(7, 10, 'C', 1),
(7, 11, 'D', 1),
(8, 4, 'A', 1),
(8, 5, 'E', 1),
(8, 9, 'B', 1),
(8, 7, 'B', 2),
(8, 2, 'C', 1),
(8, 11, 'D', 1),
(9, 4, 'A', 1),
(9, 9, 'B', 1),
(9, 7, 'B', 2),
(9, 12, 'C', 1),
(9, 11, 'D', 1),
(9, 5, 'E', 1),
(10, 4, 'A', 1),
(10, 13, 'B', 1),
(10, 7, 'B', 2),
(10, 8, 'C', 1),
(10, 5, 'E', 1),
(11, 4, 'A', 1),
(11, 13, 'B', 1),
(11, 7, 'B', 2),
(11, 14, 'C', 1),
(11, 15, 'D', 1),
(11, 5, 'E', 1),
(12, 4, 'A', 1),
(12, 13, 'B', 1),
(12, 7, 'B', 2),
(12, 16, 'C', 1),
(12, 15, 'D', 1),
(12, 5, 'E', 1),
(13, 4, 'A', 1),
(13, 13, 'B', 1),
(13, 7, 'B', 2),
(13, 16, 'C', 1),
(13, 5, 'E', 1),
(13, 17, 'D', 1),
(14, 4, 'A', 1),
(14, 7, 'B', 2),
(14, 8, 'C', 1),
(14, 5, 'E', 1),
(14, 18, 'B', 1),
(15, 4, 'A', 1),
(15, 7, 'B', 2),
(15, 19, 'C', 1),
(15, 5, 'E', 1),
(15, 18, 'B', 1),
(15, 20, 'D', 1),
(16, 4, 'A', 1),
(16, 7, 'B', 2),
(16, 21, 'C', 1),
(16, 20, 'D', 1),
(16, 5, 'E', 1),
(16, 18, 'B', 1),
(17, 4, 'A', 1),
(17, 18, 'B', 1),
(17, 7, 'B', 2),
(17, 22, 'C', 1),
(17, 23, 'D', 1),
(17, 5, 'E', 1),
(18, 4, 'A', 1),
(18, 5, 'E', 1),
(18, 7, 'B', 1),
(18, 12, 'C', 1);

-- 
-- Volcar la base de datos para la tabla `/*prefijo_db*/pagina`
-- 

INSERT INTO `/*prefijo_db*/pagina` (`id_pagina`, `nombre`, `descripcion`, `modulo`, `nivel`) VALUES 
(1, 'index', 'Pagina Principal del SITEM', 'general', 0),
(2, 'registro_usuario', 'Formulario General para el registro de usuarios', 'GENERAL', 0),
(3, 'seleccionar_rol', 'Pagina para seleccionar roles', 'GENERAL', 0),
(4, 'registro_exito', 'Pagina para mostrar mensaje de exito al registrar un usuario.', 'GENERAL', 0),
(5, 'administrador', 'Pagina Principal del Modulo de Administracion', 'ADMINISTRACION', 7),
(6, 'logout', 'Pagina intermedia para gestionar la terminacion de sesiones', 'GENERAL', 0),
(7, 'administrar_usuario', 'Pagina para administrar usuarios', 'ADMINISTRACION', 7),
(8, 'registro_admin_usuario', 'Pagina para el registro y la edicion de usuarios desde el subsistema de administracion', 'ADMINISTRACION', 7),
(9, 'borrar_usuario', 'Pagina con mensaje de confirmacion para borrar usuarios', 'ADMINISTRACION', 7),
(10, 'entidad', 'Pagina principal del modulo de entidades de salud', 'ENTIDADES', 1),
(11, 'administrar_entidad', 'Pagina para mostrar el listado de entidades registradas.', 'ENTIDADES', 1),
(12, 'registro_entidad', 'Formulario para el registro de entidades de salud.', 'ENTIDADES', 1),
(13, 'informacion_entidad', 'Pagina principal para la edicion de la informacion de la entidad', 'ENTIDADES', 1),
(14, 'principal_servicios', 'Pagina principal subsistema servicios medicos', 'SERVICIOS', 2),
(15, 'administrar_especialidad', 'Pagina para mostrar el listado de especialidades registradas.', 'SERVICIOS', 2),
(16, 'registro_especialidad', '', 'SERVICIOS', 2),
(17, 'administrar_procedimiento', 'Pagina para mostrar el listado de procedimientos medicos', 'SERVICIOS', 2),
(18, 'borrar_registro', 'Pagina general para la eliminacion de registros en el sistema.', 'GENERAL', 0);

-- 
-- Volcar la base de datos para la tabla `/*prefijo_db*/subsistema`
-- 

INSERT INTO `/*prefijo_db*/subsistema` (`id_subsistema`, `nombre`, `etiqueta`, `id_pagina`, `observacion`) VALUES 
(7, 'Administrador', 'Administrador', 5, 'Subsistema para el administrador.'),
(1, 'Entidades de Salud', 'Entidades de Salud', 10, 'Subsistema para administrar la informaciÃ³n de las entidades de salud: red el&eacute;ctricas, telef&oacute;nica, de datos, profesionales adscritos, servicios prestados, dependencias, sedes, equipos con los que cuenta.'),
(2, 'Servicios M&eacute;dicos', 'Servicios M&eacute;dicos', 14, 'Subsistema de Servicios M&eacute;dicos: Un compilado de aplicaciones web que apoyan la labor de especialistas - tesauro/cat&aacute;logo de enfermedades, medicamentos, especialidades m&eacute;dicas, directorio de profesionales, porcedimientos, historia cl&iacute;nica, consulta remota.'),
(3, 'Equipos M&eacute;dicos', 'Equipos M&eacute;dicos', 0, 'Subsistema Equipos M&eacute;dicos: Administraci&oacute;n de fichas t&eacute;nicas e informaci&oacute;n de quipos usados en medicina. Se tiene especial &eacute;nfasis en aquellos que usan tecnolog&iacute;s de interconexi&oacute;n e inform&aacute;tica.'),
(4, 'Empresas Prestadoras de Servicios de Telecomunicaciones', 'Operadores de Telecomunicaciones', 0, 'Subsistema Operadores de Telecomunicaciones: Para la administraci&oacute;n de informaci&oacute;n de las empresas prestadoras de servicios de telecomunicaciones: Datos b&aacute;sicos, servicios, equipos disponibles, planes, cubrimiento, tarifas, infraestructura, tecnolog&iacute;as ofrecidas.'),
(5, 'Proyectos de Telemedicina', 'Proyectos de Telemedicina', 0, 'Subssitema Proyectos de Telemedicina: Administracion de informacion relativa a proyectos que provean servicos de salud, medicina y educacion medica a traves de redes teleinformaticas: Informacion Basica - Ficha General de Proyecto, Integrantes, Objetivos, resultados. AdemÃ¡s cat&aacute;logo de publicaciones, eventos en el area, asociaciones, empresas y sitioes web relacionados con el tema de la telemedicina.  '),
(6, 'Tecnolog&iacute;as de Interconexi&oacute;n', 'Tecnolog&iacute;as de Interconexi&oacute;n', 0, 'Subsistema Tecnolog&iacute;as de Interconexi&oacute;n: Administraci&oacute;n de informacion acerca de las tecnologias de interconexion - protocolos, disponibles para la provision de servicios medicos usando teleinformatica: Informacion Basica - conjunto de protocolos, descripcion de servicios, etc. Agrupados genericamente sobre el modelo de referencia OSI.');
